src/main/java/br/com/emmanuelneri/monolitica/controller/MenuController.java
package br.com.emmanuelneri.monolitica.controller;

import br.com.emmanuelneri.monolitica.model.Usuario;
import br.com.emmanuelneri.monolitica.util.ApplicationProperty;
import br.com.emmanuelneri.monolitica.util.anotations.UsuarioLogado;

import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;

@Named
@RequestScoped
public class MenuController {

    @Inject
    private ApplicationProperty applicationProperty;

    @Inject
    @UsuarioLogado
    private Usuario usuario;

    public String getNomeProjeto() {
        return applicationProperty.getNomeProjeto();
    }

    public Usuario getUsuario() {
        return usuario;
    }
}

src/main/webapp/pages/commons/template.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets">

<h:head>
    <title>Portal</title>
    <meta content='text/html; charset=UTF-8' http-equiv="Content-Type" />

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
</h:head>

<h:body>

    <h:form id="formMenu">
        <nav class="navbar navbar-fixed-top navbar-inverse">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="#">#{menuController.nomeProjeto}</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Cadastros <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><h:commandLink value="Cadastro de Cliente" action="pretty:cadastro-cliente" /></li>
                                <li><h:commandLink value="Cadastro de Modelo" action="pretty:cadastro-modelo" /></li>
                                <li><h:commandLink value="Cadastro de Veículo" action="pretty:cadastro-veiculo" /></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Pedido <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><h:commandLink value="Cadastro Pedido" action="pretty:cadastro-pedido" /></li>
                                <li><h:commandLink value="Consulta Pedido" action="pretty:consulta-pedido" /></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Relatórios <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><h:commandLink value="Top Clientes" action="pretty:top-clientes" /></li>
                                <li><h:commandLink value="Top Veículos" action="pretty:top-veiculos" /></li>
                            </ul>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="#">#{menuController.usuario.email}</a></li>
                        <li><a href="#">Sair</a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </h:form>

    <br />

    <div class="container-fluid">
        <p:growl autoUpdate="true" sticky="true" />
        <ui:insert name="conteudo" />
    </div>


</h:body>

</html>