src/main/java/br/com/emmanuelneri/monolitica/model/Usuario.java
package br.com.emmanuelneri.monolitica.model;

import br.com.emmanuelneri.monolitica.util.Model;
import org.apache.shiro.crypto.hash.Sha256Hash;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;

@Entity
@Table(uniqueConstraints = {
        @UniqueConstraint(name = "usuario_uk", columnNames ={"email"})
})
@NamedQueries(value = {
        @NamedQuery(name = "Usuario.findByEmail", query = "select u from Usuario u where u.email = :email"),
})
public class Usuario implements Model<Long> {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @NotNull
    @Column(length = 100)
    private String email;

    @NotNull
    private String senha;

    @Override
    public Long getId() {
        return id;
    }

    public String getNome() {
        return email;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getSenha() {
        return senha;
    }

    public void setSenha(String senha) {
        this.senha = new Sha256Hash(senha).toHex();
    }
}

src/main/java/br/com/emmanuelneri/monolitica/controller/PedidoController.java
package br.com.emmanuelneri.monolitica.controller;

import br.com.emmanuelneri.monolitica.exception.ValidationException;
import br.com.emmanuelneri.monolitica.model.Cliente;
import br.com.emmanuelneri.monolitica.model.ItemPedido;
import br.com.emmanuelneri.monolitica.model.Modelo;
import br.com.emmanuelneri.monolitica.model.Pedido;
import br.com.emmanuelneri.monolitica.model.Usuario;
import br.com.emmanuelneri.monolitica.model.Veiculo;
import br.com.emmanuelneri.monolitica.model.enuns.Marca;
import br.com.emmanuelneri.monolitica.service.ClienteService;
import br.com.emmanuelneri.monolitica.service.ModeloService;
import br.com.emmanuelneri.monolitica.service.PedidoService;
import br.com.emmanuelneri.monolitica.service.VeiculoService;
import br.com.emmanuelneri.monolitica.util.anotations.UsuarioLogado;
import com.ocpsoft.pretty.faces.annotation.URLAction;
import com.ocpsoft.pretty.faces.annotation.URLMapping;
import com.ocpsoft.pretty.faces.annotation.URLMappings;
import org.omnifaces.util.Messages;

import javax.annotation.PostConstruct;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.List;
import java.util.Map;

@Named
@ViewScoped
@URLMappings(mappings = {
        @URLMapping(id = "cadastro-pedido", pattern = "/pedido/", viewId = "/pages/pedido/cadastro-pedido.xhtml"),
        @URLMapping(id = "editar-pedido", pattern = "/pedido/visualizar/#{pedidoController.idPedido}/", viewId = "/pages/pedido/cadastro-pedido.xhtml")
})
public class PedidoController implements Serializable {

    private List<Cliente> clientes;
    private List<Marca> marcas;
    private Map<Marca, Collection<Modelo>> modeloPorMarca;
    private Map<Modelo, Collection<Veiculo>> veiculosPorModelo;

    private Pedido pedido;
    private Marca marca;
    private Modelo modelo;
    private Veiculo veiculo;

    private BigDecimal valorUnitario;
    private int quantidade = 0;

    private Long idPedido;

    @Inject
    @UsuarioLogado
    private Usuario usuario;

    @Inject
    private PedidoService pedidoService;

    @Inject
    private ClienteService clienteService;

    @Inject
    private ModeloService modeloService;

    @Inject
    private VeiculoService veiculoService;

    @PostConstruct
    public void init() {
        inicializarCombos();
    }

    @URLAction(mappingId = "cadastro-pedido", onPostback = false)
    public void initCadastro() {
        pedido = new Pedido(usuario);
        inicializarItem();
    }

    @URLAction(mappingId = "editar-pedido", onPostback = false)
    public void initEditar() {
       pedido = pedidoService.findPedidoCompletoById(idPedido);
    }

    public void adicionarItem() {
        this.pedido.adicionarItem(valorUnitario, quantidade, veiculo);
        inicializarItem();
    }

    public void removerItem(ItemPedido itemPedido) {
        this.pedido.removerItem(itemPedido);
    }

    public void salvar() {
        try {
            pedidoService.salvar(pedido);
            Messages.addInfo(null, "Pedido salvo com sucesso!");
        } catch (ValidationException vex) {
            Messages.addError(null, vex.getMessage());
        }
    }

    public void finalizar() {
        pedidoService.finalizar(pedido);
        Messages.addInfo(null, "Pedido finalizado com sucesso!");
    }

    public boolean isPodeEditarPedido() {
        return pedido.isPedidoEditavel();
    }

    public boolean isPodeFinalizarPedido() {
        return pedido.getId() != null;
    }

    private void inicializarItem() {
        valorUnitario = BigDecimal.ZERO;
        quantidade = 0;
        veiculo = null;
        modelo = null;
        marca = null;
    }

    private void inicializarCombos() {
        clientes = clienteService.findAll();
        marcas = Arrays.asList(Marca.values());
        modeloPorMarca = modeloService.findModelosPorMarca();
        veiculosPorModelo = veiculoService.findVeiculosPorModelo();
    }

    public Collection<Modelo> getModelos() {
        if(marca != null) {
            return modeloPorMarca.get(marca);
        }
        return Collections.emptyList();
    }

    public Collection<Veiculo> getVeiculos() {
        if(modelo != null) {
            return veiculosPorModelo.get(modelo);
        }
        return Collections.emptyList();
    }

    public List<Marca> getMarcas() {
        return marcas;
    }

    public Long getIdPedido() {
        return idPedido;
    }

    public void setIdPedido(Long idPedido) {
        this.idPedido = idPedido;
    }

    public Pedido getPedido() {
        return pedido;
    }

    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }

    public List<Cliente> getClientes() {
        return clientes;
    }

    public Marca getMarca() {
        return marca;
    }

    public void setMarca(Marca marca) {
        this.marca = marca;
    }

    public Modelo getModelo() {
        return modelo;
    }

    public void setModelo(Modelo modelo) {
        this.modelo = modelo;
    }

    public Veiculo getVeiculo() {
        return veiculo;
    }

    public void setVeiculo(Veiculo veiculo) {
        this.veiculo = veiculo;
    }

    public BigDecimal getValorUnitario() {
        return valorUnitario;
    }

    public void setValorUnitario(BigDecimal valorUnitario) {
        this.valorUnitario = valorUnitario;
    }

    public int getQuantidade() {
        return quantidade;
    }

    public void setQuantidade(int quantidade) {
        this.quantidade = quantidade;
    }

}

src/main/java/br/com/emmanuelneri/monolitica/util/AbstractCrudController.java
package br.com.emmanuelneri.monolitica.util;

import org.omnifaces.util.Messages;

import java.io.Serializable;
import java.util.List;

public abstract class AbstractCrudController<T extends Model> implements Serializable {

    private List<T> lista;

    protected abstract GenericService getService();
    protected abstract String getNomeCadastro();
    protected abstract void inicializarObjeto();
    public abstract T getObjeto();
    public abstract T setObjeto(T t);

    @SuppressWarnings("unchecked")
    public void salvar() {
        getService().save(getObjeto());
        buscar();
        inicializarObjeto();
        Messages.addInfo(null, getNomeCadastro() + " salvo com sucesso!");
    }

    @SuppressWarnings("unchecked")
    public void excluir(T t) {
        getService().remove(t);
        buscar();
        inicializarObjeto();
        Messages.addInfo(null, getNomeCadastro() + " excluido com sucesso!");
    }

    @SuppressWarnings("unchecked")
    public void editar(T t) {
        setObjeto(t);
    }

    @SuppressWarnings("unchecked")
    public void buscar() {
       lista = getService().findAll();
    }

    public List<T> getLista() {
        return lista;
    }

}

src/main/webapp/pages/cadastros/cadastro-cliente.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                template="/pages/commons/template.xhtml">

<ui:define name="conteudo">

    <h1>Cadastro de Cliente</h1>

    <h:form id="form">
        <p:panel header="Cadastro" id="panelCadastro">
            <h:panelGrid columns="2">
                <h:outputLabel value="Nome: "/>
                <h:inputText value="#{clienteController.objeto.nome}" />

                <h:outputLabel value="CPF / CNPJ: "/>
                <h:inputText value="#{clienteController.objeto.cpfCnpj}" />
            </h:panelGrid>

            <p:commandButton value="Salvar" action="#{clienteController.salvar}"
                             update="panelCadastro panelListagem" process="@this panelCadastro"/>
        </p:panel>

        <p:panel id="panelListagem" header="Listagem de Clientes">
            <p:dataTable value="#{clienteController.lista}" var="cliente" paginator="true"
                         rows="20">
                <p:column headerText="Nome">
                    <h:outputText value="#{cliente.nome}"/>
                </p:column>
                <p:column headerText="CPF / CNPJ">
                    <h:outputText value="#{cliente.cpfCnpj}"/>
                </p:column>
                <p:column headerText="Opções">
                    <p:commandButton value="Editar" action="#{clienteController.editar(cliente)}"
                                     update=":form:panelCadastro" process="@this"/>
                    <p:commandButton value="Excluir" action="#{clienteController.excluir(cliente)}"
                                     update=":form:panelCadastro :form:panelListagem" process="@this"/>
                </p:column>
            </p:dataTable>
        </p:panel>
    </h:form>

</ui:define>

</ui:composition>

src/main/webapp/pages/cadastros/cadastro-modelo.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                xmlns:f="http://java.sun.com/jsf/core"
                template="/pages/commons/template.xhtml">

    <ui:define name="conteudo">

        <h1>Cadastro de Modelo</h1>

        <h:form id="form">
            <p:panel header="Cadastro" id="panelCadastro">
                <h:panelGrid columns="2">
                    <h:outputLabel value="Nome: "/>
                    <h:inputText value="#{modeloController.objeto.nome}" />

                    <h:outputLabel value="Marca: "/>
                    <h:selectOneMenu value="#{modeloController.objeto.marca}"
                            converter="omnifaces.GenericEnumConverter">
                        <f:selectItem itemLabel="Selecione" itemValue="#{null}"/>
                        <f:selectItems value="#{modeloController.marcas}" var="marca"
                                       itemValue="#{marca}" itemLabel="#{marca.descricao}" />
                        <f:ajax event="change" execute="@this" />
                    </h:selectOneMenu>
                </h:panelGrid>

                <p:commandButton value="Salvar" action="#{modeloController.salvar}"
                                 update="panelCadastro panelListagem" process="@this panelCadastro"/>
            </p:panel>

            <p:panel id="panelListagem" header="Listagem de Modelos">
                <p:dataTable value="#{modeloController.lista}" var="modelo" paginator="true"
                             rows="20">
                    <p:column headerText="Nome">
                        <h:outputText value="#{modelo.nome}"/>
                    </p:column>
                    <p:column headerText="Marca">
                        <h:outputText value="#{modelo.marca.descricao}"/>
                    </p:column>
                    <p:column headerText="Opções">
                        <p:commandButton value="Editar" action="#{modeloController.editar(modelo)}"
                                         update=":form:panelCadastro" process="@this"/>
                        <p:commandButton value="Excluir" action="#{modeloController.excluir(modelo)}"
                                         update=":form:panelCadastro :form:panelListagem" process="@this"/>
                    </p:column>
                </p:dataTable>
            </p:panel>
        </h:form>

    </ui:define>

</ui:composition>

src/main/webapp/pages/cadastros/cadastro-veiculo.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                xmlns:f="http://java.sun.com/jsf/core"
                template="/pages/commons/template.xhtml">

    <ui:define name="conteudo">

        <h1>Cadastro de Veículo</h1>

        <h:form id="form">
            <p:panel header="Cadastro" id="panelCadastro">
                <h:panelGrid columns="2">
                    <h:outputLabel value="Nome: "/>
                    <h:inputText value="#{veiculoController.objeto.nome}" />

                    <h:outputLabel value="Modelo: "/>
                    <h:selectOneMenu value="#{veiculoController.objeto.modelo}"
                                     converter="genericEntityConverter">
                        <f:selectItem itemLabel="Selecione" itemValue="#{null}"/>
                        <f:selectItems value="#{veiculoController.modelos}" var="modelo"
                                       itemValue="#{modelo}" itemLabel="#{modelo.nome}" />
                        <f:ajax event="change" execute="@this" />
                    </h:selectOneMenu>
                </h:panelGrid>

                <p:commandButton value="Salvar" action="#{veiculoController.salvar}"
                                 update="panelCadastro panelListagem" process="@this panelCadastro"/>
            </p:panel>

            <p:panel id="panelListagem" header="Listagem de Veículos">
                <p:dataTable value="#{veiculoController.lista}" var="veiculo" paginator="true"
                        rows="20">
                    <p:column headerText="Nome">
                        <h:outputText value="#{veiculo.nome}"/>
                    </p:column>
                    <p:column headerText="Modelo">
                        <h:outputText value="#{veiculo.modelo.nome}"/>
                    </p:column>
                    <p:column headerText="Marca">
                        <h:outputText value="#{veiculo.modelo.marca.descricao}"/>
                    </p:column>
                    <p:column headerText="Opções">
                        <p:commandButton value="Editar" action="#{veiculoController.editar(veiculo)}"
                                         update=":form:panelCadastro" process="@this"/>
                        <p:commandButton value="Excluir" action="#{veiculoController.excluir(veiculo)}"
                                         update=":form:panelCadastro :form:panelListagem" process="@this"/>
                    </p:column>
                </p:dataTable>
            </p:panel>
        </h:form>

    </ui:define>

</ui:composition>