src/main/java/br/com/emmanuelneri/monolitica/model/Pedido.java
package br.com.emmanuelneri.monolitica.model;

import br.com.emmanuelneri.monolitica.model.enuns.SituacaoPedido;
import br.com.emmanuelneri.monolitica.util.Model;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.validation.constraints.NotNull;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

@Entity
@NamedQueries({
        @NamedQuery(name = "Pedido.findPedidoCompletoById", query = "select p from Pedido p JOIN FETCH p.itens where p.id = :id"),
        @NamedQuery(name = "Pedido.findTopClientes", query = "select new br.com.emmanuelneri.monolitica.vo.ClienteRankingVo(c, count(i.quantidade), sum(i.valorTotal)) from Pedido p join p.cliente c join p.itens i where p.situacaoPedido <> 'CANCELADO' group by c order by sum(i.valorTotal) desc"),
        @NamedQuery(name = "Pedido.findTopVeiculo", query = "select new br.com.emmanuelneri.monolitica.vo.VeiculoRankingVo(v, count(i.quantidade)) from Pedido p join p.itens i join i.veiculo v where p.situacaoPedido <> 'CANCELADO' group by v order by count(i.quantidade) desc")
})
public class Pedido implements Model<Long>  {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @NotNull
    @Column(name = "data_criacao")
    private LocalDate dataCriacao = LocalDate.now();

    @Column(name = "data_finalizacao")
    private LocalDate dataFinalizacao;

    @NotNull
    @Column(name = "valor_total")
    private BigDecimal valorTotal = BigDecimal.ZERO;

    @NotNull
    @ManyToOne
    @JoinColumn(name = "id_cliente")
    private Cliente cliente;

    @NotNull
    @ManyToOne
    @JoinColumn(name = "id_usuario")
    private Usuario usuario;

    @NotNull
    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @JoinColumn(name = "id_pedido")
    private List<ItemPedido> itens = new ArrayList<>();

    @NotNull
    @Enumerated(EnumType.STRING)
    private SituacaoPedido situacaoPedido = SituacaoPedido.ABERTO;

    public Pedido() {
    }

    public Pedido(Usuario usuario) {
        this.usuario = usuario;
    }

    public void adicionarItem(BigDecimal valorUnitario, int quantidade, Veiculo veiculo) {
        final ItemPedido itemPedido = new ItemPedido(valorUnitario, quantidade, veiculo);
        this.itens.add(itemPedido);
        this.valorTotal = this.valorTotal.add(itemPedido.getValorTotal());
    }

    public void removerItem(ItemPedido itemPedido) {
        this.itens.remove(itemPedido);
        this.valorTotal = this.valorTotal.subtract(itemPedido.getValorTotal());
    }

    @Override
    public Long getId() {
        return id;
    }

    public LocalDate getDataCriacao() {
        return dataCriacao;
    }

    public void setDataCriacao(LocalDate dataCriacao) {
        this.dataCriacao = dataCriacao;
    }

    public LocalDate getDataFinalizacao() {
        return dataFinalizacao;
    }

    public void setDataFinalizacao(LocalDate dataFinalizacao) {
        this.dataFinalizacao = dataFinalizacao;
    }

    public BigDecimal getValorTotal() {
        return valorTotal;
    }

    public void setValorTotal(BigDecimal valorTotal) {
        this.valorTotal = valorTotal;
    }

    public Cliente getCliente() {
        return cliente;
    }

    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    public Usuario getUsuario() {
        return usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    public List<ItemPedido> getItens() {
        return itens;
    }

    public void setItens(List<ItemPedido> itens) {
        this.itens = itens;
    }

    public SituacaoPedido getSituacaoPedido() {
        return situacaoPedido;
    }

    public void setSituacaoPedido(SituacaoPedido situacaoPedido) {
        this.situacaoPedido = situacaoPedido;
    }

    public boolean isPedidoEditavel() {
        return getSituacaoPedido() == SituacaoPedido.ABERTO;
    }
}

src/main/java/br/com/emmanuelneri/monolitica/model/Usuario.java
package br.com.emmanuelneri.monolitica.model;

import br.com.emmanuelneri.monolitica.util.Model;
import org.apache.shiro.crypto.hash.Sha256Hash;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;

@Entity
@Table(uniqueConstraints = {
        @UniqueConstraint(name = "usuario_uk", columnNames ={"email"})
})
@NamedQueries(value = {
        @NamedQuery(name = "Usuario.findByEmail", query = "select u from Usuario u where u.email = :email"),
})
public class Usuario implements Model<Long> {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @NotNull
    @Column(length = 100)
    private String email;

    @NotNull
    private String senha;

    @Override
    public Long getId() {
        return id;
    }

    public String getNome() {
        return email;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getSenha() {
        return senha;
    }

    public void setSenha(String senha) {
        this.senha = new Sha256Hash(senha).toHex();
    }
}

src/main/java/br/com/emmanuelneri/monolitica/controller/ConsultaPedidoController.java
package br.com.emmanuelneri.monolitica.controller;

import br.com.emmanuelneri.monolitica.model.Pedido;
import br.com.emmanuelneri.monolitica.service.PedidoService;
import com.ocpsoft.pretty.faces.annotation.URLAction;
import com.ocpsoft.pretty.faces.annotation.URLMapping;
import com.ocpsoft.pretty.faces.annotation.URLMappings;

import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import java.io.Serializable;
import java.util.List;

@Named
@ViewScoped
@URLMappings(mappings = {
        @URLMapping(id = "consulta-pedido", pattern = "/pedido/consulta/", viewId = "/pages/pedido/consulta-pedido.xhtml")
})
public class ConsultaPedidoController implements Serializable {

    private List<Pedido> pedidos;

    @Inject
    private PedidoService pedidoService;

    @URLAction(mappingId = "consulta-pedido", onPostback = false)
    public void initConsulta() {
        pedidos = pedidoService.findAll();
    }

    public List<Pedido> getPedidos() {
        return pedidos;
    }
}

src/main/java/br/com/emmanuelneri/monolitica/controller/PedidoController.java
package br.com.emmanuelneri.monolitica.controller;

import br.com.emmanuelneri.monolitica.exception.ValidationException;
import br.com.emmanuelneri.monolitica.model.Cliente;
import br.com.emmanuelneri.monolitica.model.ItemPedido;
import br.com.emmanuelneri.monolitica.model.Modelo;
import br.com.emmanuelneri.monolitica.model.Pedido;
import br.com.emmanuelneri.monolitica.model.Usuario;
import br.com.emmanuelneri.monolitica.model.Veiculo;
import br.com.emmanuelneri.monolitica.model.enuns.Marca;
import br.com.emmanuelneri.monolitica.service.ClienteService;
import br.com.emmanuelneri.monolitica.service.ModeloService;
import br.com.emmanuelneri.monolitica.service.PedidoService;
import br.com.emmanuelneri.monolitica.service.VeiculoService;
import br.com.emmanuelneri.monolitica.util.anotations.UsuarioLogado;
import com.ocpsoft.pretty.faces.annotation.URLAction;
import com.ocpsoft.pretty.faces.annotation.URLMapping;
import com.ocpsoft.pretty.faces.annotation.URLMappings;
import org.omnifaces.util.Messages;

import javax.annotation.PostConstruct;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.List;
import java.util.Map;

@Named
@ViewScoped
@URLMappings(mappings = {
        @URLMapping(id = "cadastro-pedido", pattern = "/pedido/", viewId = "/pages/pedido/cadastro-pedido.xhtml"),
        @URLMapping(id = "editar-pedido", pattern = "/pedido/visualizar/#{pedidoController.idPedido}/", viewId = "/pages/pedido/cadastro-pedido.xhtml")
})
public class PedidoController implements Serializable {

    private List<Cliente> clientes;
    private List<Marca> marcas;
    private Map<Marca, Collection<Modelo>> modeloPorMarca;
    private Map<Modelo, Collection<Veiculo>> veiculosPorModelo;

    private Pedido pedido;
    private Marca marca;
    private Modelo modelo;
    private Veiculo veiculo;

    private BigDecimal valorUnitario;
    private int quantidade = 0;

    private Long idPedido;

    @Inject
    @UsuarioLogado
    private Usuario usuario;

    @Inject
    private PedidoService pedidoService;

    @Inject
    private ClienteService clienteService;

    @Inject
    private ModeloService modeloService;

    @Inject
    private VeiculoService veiculoService;

    @PostConstruct
    public void init() {
        inicializarCombos();
    }

    @URLAction(mappingId = "cadastro-pedido", onPostback = false)
    public void initCadastro() {
        pedido = new Pedido(usuario);
        inicializarItem();
    }

    @URLAction(mappingId = "editar-pedido", onPostback = false)
    public void initEditar() {
       pedido = pedidoService.findPedidoCompletoById(idPedido);
    }

    public void adicionarItem() {
        this.pedido.adicionarItem(valorUnitario, quantidade, veiculo);
        inicializarItem();
    }

    public void removerItem(ItemPedido itemPedido) {
        this.pedido.removerItem(itemPedido);
    }

    public void salvar() {
        try {
            pedidoService.salvar(pedido);
            Messages.addInfo(null, "Pedido salvo com sucesso!");
        } catch (ValidationException vex) {
            Messages.addError(null, vex.getMessage());
        }
    }

    public void finalizar() {
        pedidoService.finalizar(pedido);
        Messages.addInfo(null, "Pedido finalizado com sucesso!");
    }

    public boolean isPodeEditarPedido() {
        return pedido.isPedidoEditavel();
    }

    public boolean isPodeFinalizarPedido() {
        return pedido.getId() != null;
    }

    private void inicializarItem() {
        valorUnitario = BigDecimal.ZERO;
        quantidade = 0;
        veiculo = null;
        modelo = null;
        marca = null;
    }

    private void inicializarCombos() {
        clientes = clienteService.findAll();
        marcas = Arrays.asList(Marca.values());
        modeloPorMarca = modeloService.findModelosPorMarca();
        veiculosPorModelo = veiculoService.findVeiculosPorModelo();
    }

    public Collection<Modelo> getModelos() {
        if(marca != null) {
            return modeloPorMarca.get(marca);
        }
        return Collections.emptyList();
    }

    public Collection<Veiculo> getVeiculos() {
        if(modelo != null) {
            return veiculosPorModelo.get(modelo);
        }
        return Collections.emptyList();
    }

    public List<Marca> getMarcas() {
        return marcas;
    }

    public Long getIdPedido() {
        return idPedido;
    }

    public void setIdPedido(Long idPedido) {
        this.idPedido = idPedido;
    }

    public Pedido getPedido() {
        return pedido;
    }

    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }

    public List<Cliente> getClientes() {
        return clientes;
    }

    public Marca getMarca() {
        return marca;
    }

    public void setMarca(Marca marca) {
        this.marca = marca;
    }

    public Modelo getModelo() {
        return modelo;
    }

    public void setModelo(Modelo modelo) {
        this.modelo = modelo;
    }

    public Veiculo getVeiculo() {
        return veiculo;
    }

    public void setVeiculo(Veiculo veiculo) {
        this.veiculo = veiculo;
    }

    public BigDecimal getValorUnitario() {
        return valorUnitario;
    }

    public void setValorUnitario(BigDecimal valorUnitario) {
        this.valorUnitario = valorUnitario;
    }

    public int getQuantidade() {
        return quantidade;
    }

    public void setQuantidade(int quantidade) {
        this.quantidade = quantidade;
    }

}

src/main/webapp/pages/pedido/cadastro-pedido.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:pretty="http://ocpsoft.com/prettyfaces"
                template="/pages/commons/template.xhtml">

    <ui:define name="conteudo">

        <h1>Pedido</h1>

        <h:form id="form">

            <h:panelGroup id="panelPedido">
                <div class="row">
                    <div class="col-md-2">
                        <h:outputLabel value="Data Criação: " />
                        <h:outputText value="#{pedidoController.pedido.dataCriacao}">
                            <f:converter converterId="localDateConverter" />
                        </h:outputText>
                    </div>

                    <div class="col-md-2">
                        <h:outputLabel value="Situação: " />
                        <h:outputText value="#{pedidoController.pedido.situacaoPedido.descricao}"/>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-4">
                        <h:outputLabel value="Cliente" />
                        <h:selectOneMenu value="#{pedidoController.pedido.cliente}" disabled="#{not pedidoController.podeEditarPedido}"
                                         converter="genericEntityConverter" styleClass="form-control">
                            <f:selectItem itemLabel="Selecione" itemValue="#{null}"/>
                            <f:selectItems value="#{pedidoController.clientes}" var="cliente"
                                           itemValue="#{cliente}" itemLabel="#{cliente.nome}" />
                            <f:ajax event="change" execute="@this" />
                        </h:selectOneMenu>
                    </div>
                </div>
            </h:panelGroup>

            <p:panel header="Itens" style="margin-top: 10px">
                <h:panelGroup layout="block" id="panelCadastroItem"
                         rendered="#{pedidoController.podeEditarPedido}">

                    <div class="row">
                        <div class="col-md-2">
                            <h:outputLabel value="Marca" />
                            <h:selectOneMenu value="#{pedidoController.marca}" styleClass="form-control"
                                             converter="omnifaces.GenericEnumConverter"
                                             required="true" requiredMessage="Selecione uma marca">
                                <f:selectItem itemLabel="Selecione" itemValue="#{null}"/>
                                <f:selectItems value="#{pedidoController.marcas}" var="marca"
                                               itemValue="#{marca}" itemLabel="#{marca.descricao}" />
                                <f:ajax event="change" execute="@this" render="comboModelo comboVeiculo"/>
                            </h:selectOneMenu>
                        </div>

                        <div class="col-md-2">
                            <h:outputLabel value="Modelo" />
                            <h:selectOneMenu id="comboModelo" value="#{pedidoController.modelo}" styleClass="form-control"
                                             converter="genericEntityConverter" disabled="#{pedidoController.marca == null}"
                                             required="true" requiredMessage="Selecione um modelo">
                                <f:selectItem itemLabel="Selecione" itemValue="#{null}"/>
                                <f:selectItems value="#{pedidoController.modelos}" var="modelo"
                                               itemValue="#{modelo}" itemLabel="#{modelo.nome}" />
                                <f:ajax event="change" execute="@this" render="comboVeiculo" />
                            </h:selectOneMenu>
                        </div>

                        <div class="col-md-2">
                            <h:outputLabel value="Veículo" />
                            <h:selectOneMenu id="comboVeiculo" value="#{pedidoController.veiculo}" styleClass="form-control"
                                             converter="genericEntityConverter"  disabled="#{pedidoController.modelo == null}"
                                             required="true" requiredMessage="Selecione um veículo">
                                <f:selectItem itemLabel="Selecione" itemValue="#{null}"/>
                                <f:selectItems value="#{pedidoController.veiculos}" var="veiculo"
                                               itemValue="#{veiculo}" itemLabel="#{veiculo.nome}" />
                            </h:selectOneMenu>
                        </div>
                    </div>

                    <div class="row" style="margin-top: 5px">
                        <div class="col-md-2">
                            <h:outputLabel value="Quantidade" />
                            <h:inputText value="#{pedidoController.quantidade}"
                                         required="true" requiredMessage="Informe uma quantidade"/>
                         </div>

                        <div class="col-md-2">
                            <h:outputLabel value="Valor Unitário" />
                            <h:inputText value="#{pedidoController.valorUnitario}"
                                         required="true" requiredMessage="Informe o valor unitário" />
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-2" style="margin-top: 5px">
                            <p:commandLink value="Adicionar Item" styleClass="btn btn-default" action="#{pedidoController.adicionarItem}"
                                    process="@this panelCadastroItem" update="tableItens panelCadastroItem"/>
                            </div>
                    </div>
                </h:panelGroup>

                <p:dataTable value="#{pedidoController.pedido.itens}" var="item" id="tableItens"
                             emptyMessage="Não há itens cadastrados" style="margin-top: 10px">
                    <p:column headerText="Veículo">
                        <h:outputText value="#{item.veiculo.nome}"/>
                    </p:column>
                    <p:column headerText="Modelo">
                        <h:outputText value="#{item.veiculo.modelo.nome}"/>
                    </p:column>
                    <p:column headerText="Marca">
                        <h:outputText value="#{item.veiculo.modelo.marca.descricao}"/>
                    </p:column>
                    <p:column headerText="Valor Unitário">
                        <h:outputText value="#{item.valorUnitario}">
                            <f:convertNumber type="currency" />
                        </h:outputText>
                    </p:column>
                    <p:column headerText="Quantidade">
                        <h:outputText value="#{item.quantidade}"/>
                    </p:column>
                    <p:column headerText="Valor Total">
                        <h:outputText value="#{item.valorTotal}">
                            <f:convertNumber type="currency" />
                        </h:outputText>
                    </p:column>
                    <p:column headerText="Ações">
                        <p:commandButton value="Remover" action="#{pedidoController.removerItem(item)}"
                                process="@this" update="tableItens" disabled="#{not pedidoController.podeEditarPedido}"/>
                    </p:column>

                    <p:columnGroup type="footer">
                        <p:row>
                            <p:column colspan="6" footerText="Total: " style="text-align: right"/>
                            <p:column footerText="#{utilController.formtValor(pedidoController.pedido.valorTotal)}" />
                        </p:row>
                    </p:columnGroup>
                </p:dataTable>
            </p:panel>

            <div class="row" style="margin-top: 10px">
                <div class="col-md-6">
                    <p:commandLink value="Salvar" action="#{pedidoController.salvar}" update="@form" process="@this panelPedido tableItens"
                                   styleClass="btn btn-primary" rendered="#{pedidoController.podeEditarPedido}">
                    </p:commandLink>
                    <p:commandLink value="Finalizar" action="#{pedidoController.finalizar}" style="margin-left: 5px " update="@form" process="@this panelPedido tableItens"
                                   styleClass="btn btn-success" rendered="#{pedidoController.podeFinalizarPedido and pedidoController.podeEditarPedido}">
                    </p:commandLink>
                    <pretty:link mappingId="consulta-pedido" styleClass="btn btn-default" style="margin-left: 5px ">
                        Voltar
                    </pretty:link>
                </div>
            </div>
        </h:form>

    </ui:define>

</ui:composition>

src/main/webapp/pages/pedido/consulta-pedido.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:pretty="http://ocpsoft.com/prettyfaces"
                template="/pages/commons/template.xhtml">

<ui:define name="conteudo">

    <h1>Consulta de Pedidos</h1>

    <h:form id="form">
        <pretty:link mappingId="cadastro-pedido" styleClass="btn btn-primary">
            Novo Pedido
        </pretty:link>

        <p:panel id="panelListagem" header="Listagem de Pedidos" style="margin-top: 10px">
            <p:dataTable value="#{consultaPedidoController.pedidos}" var="pedido"
                    emptyMessage="Não há pedidos cadastrados" paginator="true"
                         rows="10" >
                <p:column headerText="Cliente">
                    <h:outputText value="#{pedido.cliente.nome}"/>
                </p:column>
                <p:column headerText="Situação">
                    <h:outputText value="#{pedido.situacaoPedido.descricao}"/>
                </p:column>
                <p:column headerText="Valor Total">
                    <h:outputText value="#{pedido.valorTotal}">
                        <f:convertNumber type="currency"/>
                    </h:outputText>
                </p:column>
                <p:column headerText="Data Criação">
                    <h:outputText value="#{pedido.dataCriacao}">
                        <f:converter converterId="localDateConverter" />
                    </h:outputText>
                </p:column>
                <p:column headerText="Data Finalizacão">
                    <h:outputText value="#{pedido.dataFinalizacao}">
                        <f:converter converterId="localDateConverter" />
                    </h:outputText>
                </p:column>
                <p:column headerText="Opções">
                    <pretty:link mappingId="editar-pedido" styleClass="btn btn-default">
                        <f:param value="#{pedido.id}" />
                        Visualizar
                    </pretty:link>
                </p:column>
            </p:dataTable>
        </p:panel>
    </h:form>

</ui:define>

</ui:composition>